---
title: "Team_project"
author: "S01-Blue"
output: html_document
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(leaps)
library(lubridate)
```

```{r load-data}
video_game_sales <- read.csv("data/Video_Games_Sales_as_at_22_Dec_2016.csv")
release_dates <- read.csv("data/query (1).csv")

glimpse(video_game_sales)
glimpse(release_dates)
```

### What games are on more than one platform?

```{r Plat-freq-check}
GTOnePlatform <- video_game_sales %>% 
  filter(Platform %in% c("XB","X360","XOne","PS","PS2","PS3","PS4","PC")) %>% 
  group_by(Name) %>% 
  summarise(numplats = n()) %>% 
  filter(numplats>1)


```

```{r make-dataset}
GTMerge <- video_game_sales %>% 
  filter(Platform %in% c("XB","X360","XOne","PS","PS2","PS3","PS4","PC")) %>% 
  right_join(GTOnePlatform, by = c("Name" = "Name"))


```

### Total sales of game predicted by genre of game and publisher

```{r publisher-freq-check}
by_publisher <- video_game_sales %>%
  group_by(Publisher) %>% 
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>%
  top_n(5)

by_publisher
```

```{r genre-freq-check}
PBMerge <- video_game_sales %>%
  right_join(by_publisher, by = "Publisher")

by_genre <- PBMerge %>%
  group_by(Genre) %>% 
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>%
  top_n(5)

by_genre
```

```{r genre-publisher-dataset}
PBGMerge <- PBMerge %>%
  right_join(by_genre, by = "Genre")

sales_by_genre_pub <- regsubsets(Global_Sales ~ factor(Genre) + factor(Publisher), data = PBGMerge)

summary(sales_by_genre_pub)
```

```{r RatingCounts}
summary(video_game_sales$Rating)
```


```{r regressiondata}
regressiondata <- video_game_sales %>% 
  filter(Genre %in% c("Sports", "Action", "Misc", "Shooter", "Simulation") & 
                        Publisher %in% c("Electronic Arts", 
                                         "Activision", 
                                         "Namco Bandai Games",
                                         "Ubisoft",
                                         "Konami Digital Entertainment") &
           Rating %in% c("E", "E10+", "M", "T")) %>% 
  select(Genre, Publisher, Global_Sales, Rating)
  
 

regressiondata
```


```{r regressionmodel}
Model <- lm(Global_Sales ~ Genre + Publisher + Rating, data = regressiondata)

summary(Model)
```


### Best time to release a game

```{r merging-release_date-data-set}
release_dates <- release_dates %>%
  select(gameLabel, releaseDate, platformLabel) %>%
  mutate(releaseDate = str_replace_all(releaseDate, c("T00:00:00Z" = "")))%>%
  mutate(platformLabel = str_replace_all(platformLabel, c("Microsoft Windows" = "PC",
                                                          "PlayStation" = "PS",
                                                          "PlayStation 2" = "PS2",
                                                          "PlayStation 3" = "PS3",
                                                          "PlayStation 4" = "PS4",
                                                          "PlayStation Portable" = "PSP",
                                                          "PlayStation Vita" = "PSV",
                                                          "XBox" = "XB",
                                                          "Xbox One" = "XOne",
                                                          "Xbox 360" = "X360",
                                                          "Nintendo " = "",
                                                          "Super Entertainment System" = "SNES",
                                                          "Entertainment System" = "NES",
                                                          "GameCube" = "GC",
                                                          "Game Boy Advance" = "GBA",
                                                          "64" = "N64",
                                                          "Wii U" = "WiiU")))

video_game_sales_release <- video_game_sales %>%
  left_join(release_dates, by = c("Name" = "gameLabel", "Platform" = "platformLabel")) %>%
  filter(!is.na(releaseDate)) %>%
  mutate(releaseDate = ymd(releaseDate)) %>%
  filter(year(releaseDate) < 2020) %>%
  select(-Year_of_Release) %>%
  arrange(releaseDate) %>%
  distinct(Name, Platform, Global_Sales, .keep_all = TRUE)

# Can filter Year and shows sales by month
monthlysales <- video_game_sales_release %>%
  filter(between(year(releaseDate), 1990, 2000)) %>%
  group_by(month = month(releaseDate, label = TRUE)) %>%
  summarise(avg_sales_per_month = median(Global_Sales)) %>%
  ggplot(aes(x = month, y = avg_sales_per_month)) +
  geom_bar(stat = "identity") + 
  xlab("Month of Release") + 
  ylab("Average Sales Per Month")

# Can filter Month and shows by Year
yearlysales <- video_game_sales_release %>%
  filter(between(month(releaseDate), 1, 12)) %>%
  group_by(year = year(releaseDate)) %>%
  summarise(avg_sales_per_year = median(Global_Sales)) %>% 
  ggplot(aes(x = year, y = avg_sales_per_year)) +
  geom_bar(stat = "identity")  + 
  xlab("Year of Release") + 
  ylab("Average Sales Per Year")
```

```{r savingplots}
ggsave("monthlysales.png")
ggsave("yearlysales.png")
```










